#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DroidMapping.Resource", IsApplication=true)]

namespace DroidMapping
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Acr.DeviceInfo.Resource.String.ApplicationName = global::DroidMapping.Resource.String.ApplicationName;
			global::Acr.DeviceInfo.Resource.String.Hello = global::DroidMapping.Resource.String.Hello;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::DroidMapping.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::DroidMapping.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int drawer_items = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_menu = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int action_search = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int arrow = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int arrowshadow = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_drawer = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_drawer_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_drawer_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_place = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_rel = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_shield = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_sphere = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int icon1 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int iconelse = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int mm_20_aqua = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int mm_20_ash = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int mm_20_beige = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int mm_20_black = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int mm_20_blue = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int mm_20_brown = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int mm_20_crimson = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int mm_20_dark_blue = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int mm_20_dark_green = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int mm_20_gray = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int mm_20_green = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int mm_20_lime = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int mm_20_magenta = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int mm_20_nickel = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int mm_20_olive = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int mm_20_olive_drab = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int mm_20_orange = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int mm_20_pale_green = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int mm_20_pink = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int mm_20_purple = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int mm_20_red = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int mm_20_teal = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int mm_20_terracote = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int mm_20_white = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int mm_20_yellow = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ms_arts = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ms_bar = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ms_blue_pushpin = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ms_bus = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ms_cabs = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ms_camera = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ms_campfire = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ms_campground = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ms_caution = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ms_coffeehouse = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ms_convienancestore = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ms_cycling = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ms_dollar = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ms_drinking_water = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ms_earthquake = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ms_electronics = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int ms_euro = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ms_fallingrocks = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int ms_ferry = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int ms_firedept = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int ms_fishing = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int ms_flag = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int ms_gas = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ms_golfer = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int ms_grn_pushpin = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int ms_grocerystore = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int ms_groecerystore = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int ms_helicopter = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int ms_hiker = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int ms_homegardenbusiness = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int ms_horsebackriding = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int ms_hospitals = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int ms_hotsprings = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int ms_info = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int ms_info_circle = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int ms_landmarks_jp = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int ms_lodging = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int ms_ltblu_pushpin = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int ms_man = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int ms_marina = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int ms_mechanic = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int ms_motorcycling = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int ms_movies = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int ms_parkinglot = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int ms_partly_cloudy = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int ms_pharmacy_us = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int ms_phone = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int ms_picnic = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int ms_pink_pushpin = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int ms_plane = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int ms_poi = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int ms_police = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int ms_postoffice_jp = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int ms_postoffice_us = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int ms_purple_pushpin = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int ms_question = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int ms_rail = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int ms_rainy = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int ms_rangerstation = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int ms_realestate = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int ms_recycle = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int ms_red_pushpin = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int ms_restaurant = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int ms_sailing = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int ms_salon = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int ms_shopping = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int ms_ski = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int ms_snack_bar = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int ms_snowflake_simple = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int ms_sportvenue = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int ms_subway = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int ms_sunny = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int ms_swimming = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int ms_toilets = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int ms_trail = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int ms_tram = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int ms_tree = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int ms_truck = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int ms_volcano = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int ms_water = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int ms_waterfalls = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int ms_webcam = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int ms_wheel_chair_accessible = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int ms_woman = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int ms_yen = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int ms_ylw_pushpin = 2130837628;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070017
			public const int action_websearch = 2131165207;
			
			// aapt resource value: 0x7f070015
			public const int button_register = 2131165205;
			
			// aapt resource value: 0x7f070001
			public const int content_frame = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int customInfoWindow_AllianceTextView = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int customInfoWindow_DescriptionTextView = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int customInfoWindow_FractionTextView = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int customInfoWindow_LatLonTextView = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int customInfoWindow_Name = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int drawer_layout = 2131165184;
			
			// aapt resource value: 0x7f070014
			public const int editText_comment = 2131165204;
			
			// aapt resource value: 0x7f070012
			public const int editText_name = 2131165202;
			
			// aapt resource value: 0x7f07000a
			public const int gridLayout1 = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int isLoggingQuestsSwitch = 2131165193;
			
			// aapt resource value: 0x7f070003
			public const int left_drawer = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int map = 2131165186;
			
			// aapt resource value: 0x7f070010
			public const int mapHybridTypeButton = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int mapNormalTypeButton = 2131165199;
			
			// aapt resource value: 0x7f070011
			public const int mapTerrainTypeButton = 2131165201;
			
			// aapt resource value: 0x7f07000d
			public const int mapTypeRadioGroup = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int mapUpdateFrequency = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int mapUpdateLabel = 2131165195;
			
			// aapt resource value: 0x7f070016
			public const int textView = 2131165206;
			
			// aapt resource value: 0x7f07000e
			public const int textView1 = 2131165198;
			
			// aapt resource value: 0x7f070013
			public const int textView2 = 2131165203;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_navigation_drawer = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomMarkerPopupPoint = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CustomMarkerPopupQuest = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int drawer_list_item = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int fragment_actions_list = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int fragment_cmap = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int fragment_settings = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Tab = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int navigation_drawer = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040012
			public const int ActionTabConquers = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int ActionTabQuests = 2130968595;
			
			// aapt resource value: 0x7f04000d
			public const int AllObjectsMenuTitle = 2130968589;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int ConquerMenuTitle = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int DrawerAction = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int DrawerClose = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int DrawerMap = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int DrawerOpen = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int DrawerSettings = 2130968583;
			
			// aapt resource value: 0x7f040010
			public const int GPSNotDefined = 2130968592;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f04000e
			public const int LogoutMenuTitle = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int NeedInternetConnect = 2130968591;
			
			// aapt resource value: 0x7f04000b
			public const int OnlyPointsMenuTitle = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int OnlyQuestsMenuTitle = 2130968588;
			
			// aapt resource value: 0x7f040009
			public const int QuestMenuTitle = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int RefreshMenuTitle = 2130968586;
			
			// aapt resource value: 0x7f040011
			public const int Wait = 2130968593;
			
			// aapt resource value: 0x7f040016
			public const int action_websearch = 2130968598;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040017
			public const int app_not_available = 2130968599;
			
			// aapt resource value: 0x7f040015
			public const int drawer_close = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int drawer_open = 2130968596;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
